# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(766, 652)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btnBack = QtGui.QPushButton(self.centralwidget)
        self.btnBack.setMinimumSize(QtCore.QSize(0, 35))
        self.btnBack.setObjectName(_fromUtf8("btnBack"))
        self.horizontalLayout_4.addWidget(self.btnBack)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 1, 0, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.pgMenu = QtGui.QWidget()
        self.pgMenu.setObjectName(_fromUtf8("pgMenu"))
        self.gridLayout = QtGui.QGridLayout(self.pgMenu)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 12, 1, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.btnTilmeld = QtGui.QPushButton(self.pgMenu)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTilmeld.sizePolicy().hasHeightForWidth())
        self.btnTilmeld.setSizePolicy(sizePolicy)
        self.btnTilmeld.setMinimumSize(QtCore.QSize(300, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setItalic(False)
        self.btnTilmeld.setFont(font)
        self.btnTilmeld.setObjectName(_fromUtf8("btnTilmeld"))
        self.gridLayout_3.addWidget(self.btnTilmeld, 0, 1, 1, 1)
        self.btnTurnering = QtGui.QPushButton(self.pgMenu)
        self.btnTurnering.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnTurnering.setFont(font)
        self.btnTurnering.setObjectName(_fromUtf8("btnTurnering"))
        self.gridLayout_3.addWidget(self.btnTurnering, 2, 1, 1, 1)
        self.btnMad = QtGui.QPushButton(self.pgMenu)
        self.btnMad.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnMad.setFont(font)
        self.btnMad.setObjectName(_fromUtf8("btnMad"))
        self.gridLayout_3.addWidget(self.btnMad, 1, 1, 1, 1)
        self.btnSettings = QtGui.QPushButton(self.pgMenu)
        self.btnSettings.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnSettings.setFont(font)
        self.btnSettings.setObjectName(_fromUtf8("btnSettings"))
        self.gridLayout_3.addWidget(self.btnSettings, 4, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 4, 2, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem4, 5, 1, 1, 1)
        self.btnAfslut = QtGui.QPushButton(self.pgMenu)
        self.btnAfslut.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnAfslut.setFont(font)
        self.btnAfslut.setObjectName(_fromUtf8("btnAfslut"))
        self.gridLayout_3.addWidget(self.btnAfslut, 6, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 4, 0, 1, 1)
        self.btnRapport = QtGui.QPushButton(self.pgMenu)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnRapport.setFont(font)
        self.btnRapport.setObjectName(_fromUtf8("btnRapport"))
        self.gridLayout_3.addWidget(self.btnRapport, 3, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 4, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem6, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.pgMenu)
        font = QtGui.QFont()
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.pgMenu)
        self.pgTilmeld = QtGui.QWidget()
        self.pgTilmeld.setObjectName(_fromUtf8("pgTilmeld"))
        self.gridLayout_5 = QtGui.QGridLayout(self.pgTilmeld)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.pgTilmeld)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.spinPower = QtGui.QSpinBox(self.pgTilmeld)
        self.spinPower.setMaximum(1000)
        self.spinPower.setProperty("value", 65)
        self.spinPower.setObjectName(_fromUtf8("spinPower"))
        self.horizontalLayout_2.addWidget(self.spinPower)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 2, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.pgTilmeld)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 4, 1, 1, 1)
        self.btnAddTilmeld = QtGui.QPushButton(self.pgTilmeld)
        self.btnAddTilmeld.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnAddTilmeld.setFont(font)
        self.btnAddTilmeld.setObjectName(_fromUtf8("btnAddTilmeld"))
        self.gridLayout_4.addWidget(self.btnAddTilmeld, 4, 4, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_4.addItem(spacerItem7, 3, 1, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem8, 2, 5, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 2, 0, 1, 1)
        self.txtNameTilmeld = QtGui.QLineEdit(self.pgTilmeld)
        self.txtNameTilmeld.setMinimumSize(QtCore.QSize(200, 0))
        self.txtNameTilmeld.setObjectName(_fromUtf8("txtNameTilmeld"))
        self.gridLayout_4.addWidget(self.txtNameTilmeld, 2, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.pgTilmeld)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 2, 1, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem10, 2, 3, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.txtKlasse = QtGui.QLineEdit(self.pgTilmeld)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtKlasse.sizePolicy().hasHeightForWidth())
        self.txtKlasse.setSizePolicy(sizePolicy)
        self.txtKlasse.setMinimumSize(QtCore.QSize(0, 0))
        self.txtKlasse.setMaximumSize(QtCore.QSize(80, 16777215))
        self.txtKlasse.setObjectName(_fromUtf8("txtKlasse"))
        self.horizontalLayout.addWidget(self.txtKlasse)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem11)
        self.label_5 = QtGui.QLabel(self.pgTilmeld)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.comboBord = QtGui.QComboBox(self.pgTilmeld)
        self.comboBord.setObjectName(_fromUtf8("comboBord"))
        self.comboBord.addItem(_fromUtf8(""))
        self.comboBord.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.comboBord)
        self.gridLayout_4.addLayout(self.horizontalLayout, 4, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 4, 0, 1, 1)
        self.tblTilmelding = QtGui.QTableWidget(self.pgTilmeld)
        self.tblTilmelding.setMinimumSize(QtCore.QSize(0, 0))
        self.tblTilmelding.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tblTilmelding.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tblTilmelding.setObjectName(_fromUtf8("tblTilmelding"))
        self.tblTilmelding.setColumnCount(5)
        self.tblTilmelding.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblTilmelding.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblTilmelding.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblTilmelding.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblTilmelding.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblTilmelding.setHorizontalHeaderItem(4, item)
        self.tblTilmelding.horizontalHeader().setVisible(False)
        self.tblTilmelding.horizontalHeader().setCascadingSectionResizes(True)
        self.tblTilmelding.horizontalHeader().setStretchLastSection(False)
        self.tblTilmelding.verticalHeader().setVisible(False)
        self.gridLayout_5.addWidget(self.tblTilmelding, 7, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem12, 3, 0, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem13, 6, 0, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_5.addItem(spacerItem14, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.pgTilmeld)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.pgTilmeld)
        self.pgMad = QtGui.QWidget()
        self.pgMad.setObjectName(_fromUtf8("pgMad"))
        self.gridLayout_7 = QtGui.QGridLayout(self.pgMad)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        spacerItem15 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem15, 3, 0, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem16, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.pgMad)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_7.addWidget(self.label_7, 2, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem17)
        self.label_16 = QtGui.QLabel(self.pgMad)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_5.addWidget(self.label_16)
        self.txtNameMad = QtGui.QLineEdit(self.pgMad)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtNameMad.sizePolicy().hasHeightForWidth())
        self.txtNameMad.setSizePolicy(sizePolicy)
        self.txtNameMad.setMinimumSize(QtCore.QSize(250, 0))
        self.txtNameMad.setObjectName(_fromUtf8("txtNameMad"))
        self.horizontalLayout_5.addWidget(self.txtNameMad)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem18)
        self.gridLayout_7.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.tblMad = QtGui.QTableWidget(self.pgMad)
        self.tblMad.setObjectName(_fromUtf8("tblMad"))
        self.tblMad.setColumnCount(5)
        self.tblMad.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tblMad.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblMad.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblMad.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblMad.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblMad.setHorizontalHeaderItem(4, item)
        self.tblMad.horizontalHeader().setVisible(False)
        self.tblMad.verticalHeader().setVisible(False)
        self.gridLayout_7.addWidget(self.tblMad, 7, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_18 = QtGui.QLabel(self.pgMad)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_6.addWidget(self.label_18, 1, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.pgMad)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_6.addWidget(self.label_20, 3, 1, 1, 1)
        self.lblPizza = QtGui.QLabel(self.pgMad)
        self.lblPizza.setObjectName(_fromUtf8("lblPizza"))
        self.gridLayout_6.addWidget(self.lblPizza, 0, 2, 1, 1)
        self.spinBurger = QtGui.QSpinBox(self.pgMad)
        self.spinBurger.setMaximum(20)
        self.spinBurger.setObjectName(_fromUtf8("spinBurger"))
        self.gridLayout_6.addWidget(self.spinBurger, 1, 3, 1, 1)
        self.label_19 = QtGui.QLabel(self.pgMad)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_6.addWidget(self.label_19, 2, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.pgMad)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_6.addWidget(self.label_17, 0, 1, 1, 1)
        self.lblBurger = QtGui.QLabel(self.pgMad)
        self.lblBurger.setObjectName(_fromUtf8("lblBurger"))
        self.gridLayout_6.addWidget(self.lblBurger, 1, 2, 1, 1)
        self.lblCola = QtGui.QLabel(self.pgMad)
        self.lblCola.setObjectName(_fromUtf8("lblCola"))
        self.gridLayout_6.addWidget(self.lblCola, 2, 2, 1, 1)
        self.lblSamlet = QtGui.QLabel(self.pgMad)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblSamlet.setFont(font)
        self.lblSamlet.setObjectName(_fromUtf8("lblSamlet"))
        self.gridLayout_6.addWidget(self.lblSamlet, 3, 2, 1, 1)
        self.spinPizza = QtGui.QSpinBox(self.pgMad)
        self.spinPizza.setMaximum(20)
        self.spinPizza.setObjectName(_fromUtf8("spinPizza"))
        self.gridLayout_6.addWidget(self.spinPizza, 0, 3, 1, 1)
        self.spinCola = QtGui.QSpinBox(self.pgMad)
        self.spinCola.setMaximum(20)
        self.spinCola.setObjectName(_fromUtf8("spinCola"))
        self.gridLayout_6.addWidget(self.spinCola, 2, 3, 1, 1)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem19, 0, 4, 1, 1)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem20, 0, 0, 1, 1)
        self.btnBestilMad = QtGui.QPushButton(self.pgMad)
        self.btnBestilMad.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.btnBestilMad.setFont(font)
        self.btnBestilMad.setObjectName(_fromUtf8("btnBestilMad"))
        self.gridLayout_6.addWidget(self.btnBestilMad, 3, 3, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 3)
        self.gridLayout_6.setColumnStretch(1, 2)
        self.gridLayout_6.setColumnStretch(2, 2)
        self.gridLayout_6.setColumnStretch(3, 2)
        self.gridLayout_6.setColumnStretch(4, 3)
        self.gridLayout_7.addLayout(self.gridLayout_6, 5, 0, 1, 1)
        spacerItem21 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem21, 6, 0, 1, 1)
        self.stackedWidget.addWidget(self.pgMad)
        self.pgTurnering = QtGui.QWidget()
        self.pgTurnering.setObjectName(_fromUtf8("pgTurnering"))
        self.gridLayout_8 = QtGui.QGridLayout(self.pgTurnering)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        spacerItem22 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_8.addItem(spacerItem22, 3, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.pgTurnering)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_8.addWidget(self.label_8, 1, 0, 1, 1)
        spacerItem23 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_8.addItem(spacerItem23, 0, 0, 1, 1)
        self.gridLayout_13 = QtGui.QGridLayout()
        self.gridLayout_13.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_24 = QtGui.QLabel(self.pgTurnering)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_13.addWidget(self.label_24, 0, 1, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem24, 0, 4, 1, 1)
        self.comboTurnering = QtGui.QComboBox(self.pgTurnering)
        self.comboTurnering.setMinimumSize(QtCore.QSize(150, 0))
        self.comboTurnering.setObjectName(_fromUtf8("comboTurnering"))
        self.gridLayout_13.addWidget(self.comboTurnering, 0, 2, 1, 1)
        self.btnNewTurnering = QtGui.QToolButton(self.pgTurnering)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnNewTurnering.setFont(font)
        self.btnNewTurnering.setStyleSheet(_fromUtf8("background-color: green;\n"
"color: white;\n"
"margin-top: -5;\n"
"margin-bottom: -5;\n"
"margin-left: -3;\n"
"margin-right: -3;"))
        self.btnNewTurnering.setObjectName(_fromUtf8("btnNewTurnering"))
        self.gridLayout_13.addWidget(self.btnNewTurnering, 0, 3, 1, 1)
        spacerItem25 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem25, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_13, 4, 0, 1, 1)
        self.tabsTurneringer = QtGui.QTabWidget(self.pgTurnering)
        self.tabsTurneringer.setEnabled(True)
        self.tabsTurneringer.setObjectName(_fromUtf8("tabsTurneringer"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.gridLayout_14 = QtGui.QGridLayout(self.tab_1)
        self.gridLayout_14.setMargin(0)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.lblTurneringOversigt = QtGui.QTextEdit(self.tab_1)
        self.lblTurneringOversigt.setReadOnly(True)
        self.lblTurneringOversigt.setOverwriteMode(False)
        self.lblTurneringOversigt.setObjectName(_fromUtf8("lblTurneringOversigt"))
        self.gridLayout_14.addWidget(self.lblTurneringOversigt, 0, 0, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem26)
        self.btnEditTurnering = QtGui.QPushButton(self.tab_1)
        self.btnEditTurnering.setObjectName(_fromUtf8("btnEditTurnering"))
        self.horizontalLayout_6.addWidget(self.btnEditTurnering)
        self.btnDelTurnering = QtGui.QPushButton(self.tab_1)
        self.btnDelTurnering.setObjectName(_fromUtf8("btnDelTurnering"))
        self.horizontalLayout_6.addWidget(self.btnDelTurnering)
        self.gridLayout_14.addLayout(self.horizontalLayout_6, 1, 0, 1, 1)
        self.tabsTurneringer.addTab(self.tab_1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_15 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_15.setMargin(0)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.btnAddTeam = QtGui.QPushButton(self.tab_2)
        self.btnAddTeam.setObjectName(_fromUtf8("btnAddTeam"))
        self.gridLayout_15.addWidget(self.btnAddTeam, 2, 2, 1, 1)
        self.txtTeamName = QtGui.QLineEdit(self.tab_2)
        self.txtTeamName.setObjectName(_fromUtf8("txtTeamName"))
        self.gridLayout_15.addWidget(self.txtTeamName, 0, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_2)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_15.addWidget(self.label_25, 0, 0, 1, 1)
        spacerItem27 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem27, 1, 0, 1, 1)
        self.tabsTurneringer.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_16 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_16.setMargin(0)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.scrollArea = QtGui.QScrollArea(self.tab_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 98, 46))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_19 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_19.setMargin(0)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.grid_2 = QtGui.QGridLayout()
        self.grid_2.setContentsMargins(-1, -1, 0, -1)
        self.grid_2.setObjectName(_fromUtf8("grid_2"))
        spacerItem28 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.grid_2.addItem(spacerItem28, 1, 0, 1, 1)
        spacerItem29 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.grid_2.addItem(spacerItem29, 0, 0, 1, 1)
        self.layoutKampeLeft = QtGui.QVBoxLayout()
        self.layoutKampeLeft.setContentsMargins(-1, 0, -1, -1)
        self.layoutKampeLeft.setSpacing(20)
        self.layoutKampeLeft.setObjectName(_fromUtf8("layoutKampeLeft"))
        self.grid_2.addLayout(self.layoutKampeLeft, 0, 1, 1, 1)
        self.layoutKampeRight = QtGui.QVBoxLayout()
        self.layoutKampeRight.setContentsMargins(-1, 0, -1, -1)
        self.layoutKampeRight.setSpacing(20)
        self.layoutKampeRight.setObjectName(_fromUtf8("layoutKampeRight"))
        self.grid_2.addLayout(self.layoutKampeRight, 0, 2, 1, 1)
        spacerItem30 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.grid_2.addItem(spacerItem30, 0, 3, 1, 1)
        self.gridLayout_19.addLayout(self.grid_2, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_16.addWidget(self.scrollArea, 2, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.btnStartTurnering = QtGui.QPushButton(self.tab_3)
        self.btnStartTurnering.setObjectName(_fromUtf8("btnStartTurnering"))
        self.horizontalLayout_7.addWidget(self.btnStartTurnering)
        spacerItem31 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem31)
        self.gridLayout_16.addLayout(self.horizontalLayout_7, 1, 0, 1, 1)
        self.tabsTurneringer.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout_8.addWidget(self.tabsTurneringer, 5, 0, 1, 1)
        self.stackedWidget.addWidget(self.pgTurnering)
        self.pgSettings = QtGui.QWidget()
        self.pgSettings.setObjectName(_fromUtf8("pgSettings"))
        self.gridLayout_9 = QtGui.QGridLayout(self.pgSettings)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_9 = QtGui.QLabel(self.pgSettings)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_9.addWidget(self.label_9, 2, 0, 1, 1)
        spacerItem32 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem32, 3, 0, 1, 1)
        self.gridLayout_10 = QtGui.QGridLayout()
        self.gridLayout_10.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_14 = QtGui.QLabel(self.pgSettings)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_10.addWidget(self.label_14, 5, 1, 1, 1)
        spacerItem33 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_10.addItem(spacerItem33, 4, 1, 1, 1)
        self.spinColaPris = QtGui.QSpinBox(self.pgSettings)
        self.spinColaPris.setObjectName(_fromUtf8("spinColaPris"))
        self.gridLayout_10.addWidget(self.spinColaPris, 3, 2, 1, 1)
        self.spinPizzaPris = QtGui.QSpinBox(self.pgSettings)
        self.spinPizzaPris.setAccelerated(False)
        self.spinPizzaPris.setMaximum(500)
        self.spinPizzaPris.setObjectName(_fromUtf8("spinPizzaPris"))
        self.gridLayout_10.addWidget(self.spinPizzaPris, 1, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.pgSettings)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_10.addWidget(self.label_12, 2, 1, 1, 1)
        self.spinStortBord = QtGui.QSpinBox(self.pgSettings)
        self.spinStortBord.setMaximum(1000)
        self.spinStortBord.setObjectName(_fromUtf8("spinStortBord"))
        self.gridLayout_10.addWidget(self.spinStortBord, 6, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.pgSettings)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_10.addWidget(self.label_11, 0, 1, 1, 1)
        spacerItem34 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem34, 0, 0, 1, 1)
        self.spinBurgerPris = QtGui.QSpinBox(self.pgSettings)
        self.spinBurgerPris.setMaximum(500)
        self.spinBurgerPris.setObjectName(_fromUtf8("spinBurgerPris"))
        self.gridLayout_10.addWidget(self.spinBurgerPris, 2, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.pgSettings)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_10.addWidget(self.label_13, 3, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.pgSettings)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_10.addWidget(self.label_10, 1, 1, 1, 1)
        spacerItem35 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem35, 0, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.pgSettings)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_10.addWidget(self.label_15, 6, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.pgSettings)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_10.addWidget(self.label_21, 7, 1, 1, 1)
        self.spinLilleBord = QtGui.QSpinBox(self.pgSettings)
        self.spinLilleBord.setMaximum(1000)
        self.spinLilleBord.setObjectName(_fromUtf8("spinLilleBord"))
        self.gridLayout_10.addWidget(self.spinLilleBord, 7, 2, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_10, 4, 0, 1, 1)
        spacerItem36 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem36, 0, 0, 1, 1)
        spacerItem37 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem37, 10, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem38 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem38)
        self.btnGem = QtGui.QPushButton(self.pgSettings)
        self.btnGem.setMinimumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.btnGem.setFont(font)
        self.btnGem.setObjectName(_fromUtf8("btnGem"))
        self.horizontalLayout_3.addWidget(self.btnGem)
        spacerItem39 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem39)
        self.gridLayout_9.addLayout(self.horizontalLayout_3, 5, 0, 1, 1)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem40 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem40)
        self.btnDefault = QtGui.QPushButton(self.pgSettings)
        self.btnDefault.setObjectName(_fromUtf8("btnDefault"))
        self.horizontalLayout_9.addWidget(self.btnDefault)
        spacerItem41 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem41)
        self.gridLayout_9.addLayout(self.horizontalLayout_9, 7, 0, 1, 1)
        spacerItem42 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_9.addItem(spacerItem42, 6, 0, 1, 1)
        self.stackedWidget.addWidget(self.pgSettings)
        self.pgRapport = QtGui.QWidget()
        self.pgRapport.setObjectName(_fromUtf8("pgRapport"))
        self.gridLayout_11 = QtGui.QGridLayout(self.pgRapport)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        spacerItem43 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_11.addItem(spacerItem43, 0, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.pgRapport)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_11.addWidget(self.label_22, 1, 0, 1, 1)
        spacerItem44 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_11.addItem(spacerItem44, 2, 0, 1, 1)
        self.txtRapport = QtGui.QTextEdit(self.pgRapport)
        self.txtRapport.setReadOnly(True)
        self.txtRapport.setObjectName(_fromUtf8("txtRapport"))
        self.gridLayout_11.addWidget(self.txtRapport, 8, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.btnLavRapport = QtGui.QPushButton(self.pgRapport)
        self.btnLavRapport.setObjectName(_fromUtf8("btnLavRapport"))
        self.horizontalLayout_8.addWidget(self.btnLavRapport)
        spacerItem45 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem45)
        self.btnResetAll = QtGui.QPushButton(self.pgRapport)
        self.btnResetAll.setObjectName(_fromUtf8("btnResetAll"))
        self.horizontalLayout_8.addWidget(self.btnResetAll)
        self.gridLayout_11.addLayout(self.horizontalLayout_8, 4, 0, 1, 1)
        self.stackedWidget.addWidget(self.pgRapport)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 766, 31))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(5)
        self.tabsTurneringer.setCurrentIndex(0)
        QtCore.QObject.connect(self.btnAfslut, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "LanParty Administration", None))
        self.btnBack.setText(_translate("MainWindow", "Tilbage", None))
        self.btnTilmeld.setText(_translate("MainWindow", "Tilmeld", None))
        self.btnTurnering.setText(_translate("MainWindow", "Turneringer", None))
        self.btnMad.setText(_translate("MainWindow", "Mad Oversigt", None))
        self.btnSettings.setText(_translate("MainWindow", "Indstillinger", None))
        self.btnAfslut.setText(_translate("MainWindow", "Afslut", None))
        self.btnRapport.setText(_translate("MainWindow", "Rapport over Lan", None))
        self.label.setText(_translate("MainWindow", "Lan Party Administration", None))
        self.label_4.setText(_translate("MainWindow", "Strømforbrug (Watt)", None))
        self.label_3.setText(_translate("MainWindow", "Klasse", None))
        self.btnAddTilmeld.setText(_translate("MainWindow", "Tilføj", None))
        self.label_2.setText(_translate("MainWindow", "Navn", None))
        self.label_5.setText(_translate("MainWindow", "Bord", None))
        self.comboBord.setItemText(0, _translate("MainWindow", "Lille bord", None))
        self.comboBord.setItemText(1, _translate("MainWindow", "Stort bord", None))
        self.tblTilmelding.setSortingEnabled(False)
        item = self.tblTilmelding.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Navn", None))
        item = self.tblTilmelding.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Klasse", None))
        item = self.tblTilmelding.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Bord", None))
        item = self.tblTilmelding.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Strømforbrug", None))
        item = self.tblTilmelding.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Betalt", None))
        self.label_6.setText(_translate("MainWindow", "Tilmelding til Lan", None))
        self.label_7.setText(_translate("MainWindow", "Bestilling af Mad", None))
        self.label_16.setText(_translate("MainWindow", "Navn", None))
        item = self.tblMad.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Navn", None))
        item = self.tblMad.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Pizza", None))
        item = self.tblMad.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Burger", None))
        item = self.tblMad.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cola", None))
        item = self.tblMad.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Pris", None))
        self.label_18.setText(_translate("MainWindow", "Burger", None))
        self.label_20.setText(_translate("MainWindow", "Samlet pris:", None))
        self.lblPizza.setText(_translate("MainWindow", "0,-", None))
        self.label_19.setText(_translate("MainWindow", "Cola", None))
        self.label_17.setText(_translate("MainWindow", "Pizza", None))
        self.lblBurger.setText(_translate("MainWindow", "0,-", None))
        self.lblCola.setText(_translate("MainWindow", "0,-", None))
        self.lblSamlet.setText(_translate("MainWindow", "0,-", None))
        self.btnBestilMad.setText(_translate("MainWindow", "Bestil", None))
        self.label_8.setText(_translate("MainWindow", "Turneringer", None))
        self.label_24.setText(_translate("MainWindow", "Turnering:", None))
        self.btnNewTurnering.setText(_translate("MainWindow", "+", None))
        self.lblTurneringOversigt.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.btnEditTurnering.setText(_translate("MainWindow", "Rediger", None))
        self.btnDelTurnering.setText(_translate("MainWindow", "Slet", None))
        self.tabsTurneringer.setTabText(self.tabsTurneringer.indexOf(self.tab_1), _translate("MainWindow", "Oversigt", None))
        self.btnAddTeam.setText(_translate("MainWindow", "Tilføj", None))
        self.label_25.setText(_translate("MainWindow", "Holdnavn / Spillernavn:", None))
        self.tabsTurneringer.setTabText(self.tabsTurneringer.indexOf(self.tab_2), _translate("MainWindow", "Tilføj Hold", None))
        self.btnStartTurnering.setText(_translate("MainWindow", "Start Turnering", None))
        self.tabsTurneringer.setTabText(self.tabsTurneringer.indexOf(self.tab_3), _translate("MainWindow", "Kampe", None))
        self.label_9.setText(_translate("MainWindow", "Indstillinger", None))
        self.label_14.setText(_translate("MainWindow", "Tilmelding", None))
        self.label_12.setText(_translate("MainWindow", "Burger", None))
        self.label_11.setText(_translate("MainWindow", "Mad", None))
        self.label_13.setText(_translate("MainWindow", "Cola", None))
        self.label_10.setText(_translate("MainWindow", "Pizza", None))
        self.label_15.setText(_translate("MainWindow", "Stort bord", None))
        self.label_21.setText(_translate("MainWindow", "Lille bord", None))
        self.btnGem.setText(_translate("MainWindow", "Gem", None))
        self.btnDefault.setText(_translate("MainWindow", " Nulstil indstillinger", None))
        self.label_22.setText(_translate("MainWindow", "Rapport over Lan", None))
        self.btnLavRapport.setText(_translate("MainWindow", "Lav Rapport", None))
        self.btnResetAll.setText(_translate("MainWindow", "Nulstil LanParty", None))

